server:
  servlet:
    context-path: /api

spring:
  application:
    name: PhotoBlast
  rabbitmq:
    host: localhost
    port: 5672
    username: photoblast
    password: photoblast123
    virtual-host: photoblast
  data:
    redis:
      host: localhost
      port: 6379

photoblast:
  storage:
    upload-dir: uploads
    processed-dir: processed
    thumbnail-dir: thumbnails
  image:
    resize:
      width: 1920
      height: 1080
    thumbnail:
      width: 200
      height: 200
    watermark:
      path: watermark.png
      opacity: 0.3
  rabbitmq:
    queue:
      photo-process: job.photo.process
      dead-letter: job.photo.process.dlq
    exchange:
      photo: photo.exchange
    routing-key:
      photo-process: photo.process
  idempotency:
    ttl-minutes: 60
